apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: r-giyosov
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: dockeriohub/docker-flaskapp:v1
        ports:
        - containerPort: 5000
