apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: flaskapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapp
status:
  loadBalancer: {}
