apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: flask-ingress
spec:
  rules:
  - host: kube.ravshandev.uz
    http:
      paths:
      - backend:
          service:
            name: flaskapp
            port:
              number: 80
        path: /load-capability
        pathType: Exact
status:
  loadBalancer: {}
